name: Nextjs Build and Push Docker Image

on:
    push:
        branches: ["main"]
        paths:
            - 'front-next-ph2/**'

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest

        steps:
            - name: 최신 버전을 다운로드 받습니다.
              uses: actions/checkout@v4.2.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: ./front-next-ph2
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-ph2:front-latest
